# Generated by Django 4.2.5 on 2024-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ad_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
